SELECT * 
FROM customer
LIMIT 10;

-- total revenue generated by male vs. female customers
SELECT gender, SUM(purchase_amount) as revenue
FROM customer
GROUP BY gender;

-- customers who used a discount but still spent more than the average purchase amount
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes' AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer);

-- top 5 products with the highest average review rating
SELECT item_purchased, ROUND(AVG(review_rating::numeric),2) as avg_review_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_review_rating DESC
LIMIT 5;

-- average Purchase Amounts between Standard and Express Shipping
SELECT shipping_type, ROUND(AVG(purchase_amount),2)
FROM customer
WHERE shipping_type = 'Standard' OR shipping_type = 'Express'
GROUP BY shipping_type;

-- average spend and total revenue between subscribers and non-subscribers
SELECT subscription_status, COUNT(*) as total_customer, ROUND(AVG(purchase_amount),2) as avg_purchase, SUM(purchase_amount) as total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_customer, avg_purchase DESC;

-- 5 products have the highest percentage of purchases with discounts applied
SELECT item_purchased,
ROUND(100 * SUM (CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) as discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment
WITH customer_type AS (
	SELECT customer_id, previous_purchases,
	CASE 
	    WHEN previous_purchases = 1 THEN 'New'
	    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
		ELSE 'Loyal'
		END AS customer_segment
	FROM customer
)

SELECT customer_segment, COUNT(*) AS number_of_customer
FROM customer_type
GROUP BY customer_segment;

-- SELECT 
--     CASE 
--         WHEN previous_purchases = 1 THEN 'New'
--         WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
--         ELSE 'Loyal'
--     END AS customer_segment,
--     COUNT(*) AS number_of_customers
-- FROM customer
-- GROUP BY customer_segment;

-- top 3 most purchased products within each category

WITH item_count AS (
	SELECT  category,
			item_purchased,
			COUNT(customer_id) AS total_orders,
			ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
	FROM customer
	GROUP BY category, item_purchased
)

SELECT item_rank, category, item_purchased, total_orders
FROM item_count
WHERE item_rank <= 3;

-- SELECT 
--     item_purchased,
--     COUNT(*) AS total_purchases
-- FROM customer
-- GROUP BY item_purchased
-- ORDER BY total_purchases DESC
-- LIMIT 3;

-- customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe

SELECT subscription_status, COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- revenue contribution of each age group

SELECT age_group, SUM(purchase_amount) as revenue
FROM customer
GROUP BY age_group
ORDER BY revenue DESC;